### PR TITLE
Teensy40 benchmark

### PR DESCRIPTION
**Pull request by Finomnis**
Add a benchmark example for teensy 40.

May need some cleanup before merging.

### CODE REVIEW

**Comment by Finomnis** [comment]
Closed due to inactivity.

**Comment by tarcieri** [comment]
This looks potentially interesting! Sorry I didn't get around to reviewing it

**Comment by Finomnis** [comment]
> This looks potentially interesting! Sorry I didn't get around to reviewing it

No problem! Feel free to reopen. (or do I need to do that?)

**Comment by Finomnis** [comment]
Closed again due to inactivity. Feel free to reopen.

**Pull request closed without merging**
