### PR TITLE
Method for normalizing a quaternion

### PR DESCRIPTION
**Pull request by korken89**
Hi,

A simple method for normalizing a quaternion.

### CODE REVIEW

**Comment by tarcieri** [comment]
@korken89 there's already `Quaternion::norm`, so this might be a bit confusing.

It seems the terminology here has some overlap.

**Comment by korken89** [comment]
In literature the operation is commonly referred to as `normalization` (both for complex and real vectors).
But maybe you have something different in mind?

**Comment by korken89** [comment]
I noticed another thing, on the use of `norm` currently in this library, it does unfortunately not seem to coincide with literature on norms: https://en.wikipedia.org/wiki/Norm_(mathematics)
Where the current term used is `magnitude`. 
Most likely to align with literature one should rename `norm` methods to `norm_squared` and `magnitude` methods to `norm`.

This is however a breaking change. but if you'd like to see this change I can fix a PR for it.

**Comment by tarcieri** [comment]
@korken89 it's using "norm" as defined here: https://www.mathworks.com/help/aeroblks/quaternionnorm.html

Here's a whole discussion on it: https://math.stackexchange.com/questions/3174308/norm-of-quaternion

The top-rated comment says "conventions vary". Curious about your thought on that discussion. It talks about the Wikipedia article versus the definition given on the MathWorks page.

I'd prefer not to make a breaking change, but we can deprecate the `norm` method if need be.

**Comment by korken89** [comment]
Hi, on this PR was there something you wanted me to fix?

**Comment by tarcieri** [comment]
Would you agree having both `norm` and `normalize` is confusing and we should rename and/or deprecate one?

**Comment by korken89** [comment]
To me there is no overlap, `norm` is a function on an entity and `normalize` is a operation that changes the entity.

**Comment by tarcieri** [comment]
Ok let's go with it, and I guess see if it leads to confusion down the road

**Pull request merged**
